### PR TITLE
try to get openvpn.exe path from registry

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by mattock** [comment]
The idea is good, but this would be way shorter and more Powershellish way to do it:

```$Openvpn = (Get-ItemProperty 'HKLM:\SOFTWARE\OpenVPN' -Name 'exe_path').exe_path```

This was aped from [StackOverflow](http://stackoverflow.com/questions/15511809/how-do-i-get-the-value-of-a-registry-key-and-only-the-value-using-powershell#15511932).

**Comment by chipitsine** [comment]
such an approach will fail if there's no branch in registry

**Comment by chipitsine** [comment]
actually, I do not mind, if that works better, ok, let us choose that way

**Comment by mattock** [comment]
I think we can assume that OpenVPN is installed. That said, maybe it should simply exit if that command fails.

**Comment by mattock** [comment]
I implemented this in PR https://github.com/OpenVPN/openvpn-windows-test/pull/4. The default path to openvpn-gui.exe is also generated from openvpn.exe's path (exe_path).

 @chipitsine: looks good?

**Comment by chipitsine** [comment]
looks good :)

**Pull request closed without merging**
